name: flutter_qiblah_advanced_example
description: Demonstrates how to use the flutter_qiblah_advanced plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_qiblah_advanced:
    path: ../

  flutter_svg: ^2.2.3
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
